In [1]:
import tensorflow as tf
print("Version of tensorflow is : %s"%str(tf.__version__))

Version of tensorflow is : 1.15.0


In [2]:
graph1 = tf.Graph()

In [23]:
with graph1.as_default():
    a = tf.constant([5],name="constant_a")
    b = tf.constant([2],name="constant_b")
    
    add = tf.add(a,b,name="add")

In [24]:
print("a := %s\t&\tname := %s"%(str(a),a.name))
print("b := %s\t&\tname := %s"%(str(b),b.name))
print("add := %s\t&\tname := %s"%(str(add),add.name))

a := Tensor("constant_a_15:0", shape=(1,), dtype=int32)	&	name := constant_a_15:0
b := Tensor("constant_b_1:0", shape=(1,), dtype=int32)	&	name := constant_b_1:0
add := Tensor("add_9:0", shape=(1,), dtype=int32)	&	name := add_9:0


In [25]:
sess = tf.Session(graph=graph1)

In [26]:
print("Value of a := ",sess.run(a))
print("Value of b := ",sess.run(b))
print("Value of add := ",sess.run(add))

Value of a :=  [5]
Value of b :=  [2]
Value of add :=  [7]


In [34]:
with graph1.as_default():
    add_op = a+b
    sub_op = a-b
    mul = a * b

In [37]:
print("Value of add_op := ",sess.run(add_op))
print("Value of sub_op := ",sess.run(sub_op))
print("Value of mul := ",sess.run(mul))

Value of add_op :=  [7]
Value of sub_op :=  [3]
Value of mul :=  [10]


In [39]:
sess.close()

In [40]:
graph2 = tf.Graph()
with graph2.as_default():
    scalar = tf.constant(5,name="Scalar")
    vector = tf.constant([10,20,30],name="Vector")
    matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]],name="Matrix")
    tensor = tf.constant([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]],name="Tensor")

In [41]:
print("Shape of scalar := %s"%str(scalar.shape))
print("Shape of vector := %s"%str(vector.shape))
print("Shape of matrix := %s"%str(matrix.shape))
print("Shape of tensor := %s"%str(tensor.shape))

Shape of scalar := ()
Shape of vector := (3,)
Shape of matrix := (3, 3)
Shape of tensor := (2, 2, 3)


In [42]:
print("scalar := ",scalar)
print("vector := ",vector)
print("matrix := ",matrix)
print("tensor := ",tensor)

scalar :=  Tensor("Scalar:0", shape=(), dtype=int32)
vector :=  Tensor("Vector:0", shape=(3,), dtype=int32)
matrix :=  Tensor("Matrix:0", shape=(3, 3), dtype=int32)
tensor :=  Tensor("Tensor:0", shape=(2, 2, 3), dtype=int32)


In [45]:
with tf.Session(graph=graph2) as sess:
    print("\nValue of scalar :=\n%s"%str(sess.run(scalar)))
    print("\nValue of vector :=\n%s"%str(sess.run(vector)))
    print("\nValue of matrix :=\n%s"%str(sess.run(matrix)))
    print("\nValue of tensor :=\n%s"%str(sess.run(tensor)))


Value of scalar :=
5

Value of vector :=
[10 20 30]

Value of matrix :=
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Value of tensor :=
[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


In [57]:
with graph2.as_default():
    mul = tf.matmul(matrix,matrix)
    mul_op = matrix * matrix
    
    add = tf.add(matrix,matrix)
    sub = tf.subtract(matrix,matrix)

In [58]:
with tf.Session(graph=graph2) as sess:
    print("\nMatrix multipication : \n",sess.run(mul))
    print("\nElement wise operation :\n",sess.run(mul_op))
    print("\nAdd is :\n",sess.run(add))
    print("\nSubtract is :\n",sess.run(sub))


Matrix multipication : 
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Element wise operation :
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]

Add is :
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Subtract is :
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [73]:
v = tf.Variable(0)
update = tf.assign(v,v+1)

In [74]:
in_op = tf.global_variables_initializer()

In [77]:
with tf.Session() as sess:
    sess.run(in_op)
    print("Value of v := ",sess.run(v))
    for _ in range(5):
        sess.run(update)
        print("Value of v := ",sess.run(v))

Value of v :=  0
Value of v :=  1
Value of v :=  2
Value of v :=  3
Value of v :=  4
Value of v :=  5


In [78]:
a = tf.placeholder(tf.float64)
b = a * 3

In [79]:
with tf.Session() as sess:
    result = sess.run(b,feed_dict={a:3.5})
    print (result)

10.5


In [80]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[ 3.  6.  9.]
  [12. 15. 18.]
  [21. 24. 27.]
  [30. 33. 36.]]

 [[39. 42. 45.]
  [48. 51. 54.]
  [57. 60. 63.]
  [66. 69. 72.]]]
